# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pankaj_portfolio
  username: dell
  password: 123456

test:
  <<: *default
  database: pankaj_portfolio_test
  username: dell
  password: 123456

production:
  <<: *default
  database: pankaj_portfolio_production
  username: dell
  password: 123456

